### ISSUE TITLE
連番リストの提案

### ISSUE THREAD

**Issue by cwd-k2** [syuilo/aiscript#106]
`1~10` のような書き方で `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` となるような表記があると
```
for (#i =  1 ,10) { ... }
```
を
```
each (#i, 1~10) { ... }
```
として統一することも可能そう

**Comment by marihachi** [comment]
C#のEnumerable.Rangeみたいな感じね
ループ以外でも活用できて良さそう
構文については検討が必要だと思う
組み込み関数の糖衣構文とするのがきれいかな

**Comment by cwd-k2** [comment]
今の `Ops` の `+` -> `Core:add` みたいな組み込み関数の糖衣構文の状態だと `()` が必須になる？

**Comment by syuilo** [comment]
1 ~ 100 みたいに間にスペースを入れるのを許可しなかったり、1~100~200みたいに連続して使うのを禁止すればカッコ不要だと思う

**Comment by marihachi** [comment]
かっこを外して普通に書くと左再帰しちゃうので工夫しないといけない

**Comment by marihachi** [comment]
演算子の追加ではなく、eachの構文を変更する形なら簡単に実現できそ

**Comment by marihachi** [comment]
けど、普通の式で使えないのはちょっと不自然かな

**Comment by cwd-k2** [comment]
まずいのかもだけど
```
Expr <- FnCall | Ops | Term

Ops  <- Term [記号]+ Term
Term <- Literal | '(' Expr ')'
```
みたいにした場合ってどうなる？

**Comment by marihachi** [comment]
TermにOpsが含まれないので、例えば`a+b+c` とか`a+b*c` みたいな式は書けなそう。
おそらく、概ねそんな感じのアプローチで、ちょっとひねった書き方が必要になる。

**Comment by cwd-k2** [comment]
連続させたいなら
```
Ops <- Term [記号 Term]+
```
とすればよさそう？

いける気もしてきた

**Comment by marihachi** [comment]
いけるかも

**Comment by marihachi** [comment]
アクションコードで結合性も制御できそうだ

**Comment by marihachi** [comment]
単項演算子はどうだろう

**Comment by cwd-k2** [comment]
単項演算子として考えられるもの
- インクリメント・デクリメント（代替の構文あり）
- 数値の符号反転
- 真偽値の反転
の他によく利用しそうなものってある？ビット反転？

**Comment by cwd-k2** [comment]
一旦解決
