### ISSUE TITLE
ASTの全ノードを簡単にスキャンできるようにしたい

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#117]
子ノードをできるだけchildrenに持つようにして、統一的にスキャンできるように。
(if式など複数の子ノード配列を持つノード以外)

**Comment by marihachi** [comment]
ちょっと保留

**Comment by marihachi** [comment]
これやりたいけど広範囲に影響するので、落ち着いたらやる

**Comment by marihachi** [comment]
トラバーサルしたい場面が多いからノードを抽象化したい

## 案1
ノードには複数の子を持つことができる`children`プロパティを用意して、統一的にトラバーサルできるようにする。
ifのthen処理など複数の子を持つノードは`multipleNode`みたいなノードタイプを用意して一つにまとめる。
こうすれば、then、elseif、elseなど子に複数のブロックを持つノードも抽象化できる。

**Comment by marihachi** [comment]
`multipleNode`まで抽象化せずに、`else`ノードみたいな感じで子に持っても良いかも知れない。
(抽象化しすぎると、それが何かわからないので)

**Comment by marihachi** [comment]
どうするのが良いのか分からなくなってきた

**Comment by marihachi** [comment]
やっぱこのアプローチやめるか

**Comment by marihachi** [comment]
## 案2
ノードの子ノードはすべて`children`に持つ。
子ノードの種類を区別する必要がある場合(ifノードにelseノードとelseifノードを区別して持つ必要がある場合など)は、子と親の間にその区別のためのノードを追加する。

**Comment by syuilo** [comment]
その場合、今までifノードのelseを実行したかったら ifNode.else みたいにアクセスしていたところを ifNode の children からelseノードを探してくる実装にする必要がある？

**Comment by marihachi** [comment]
そうなるね
そこのコストが上がるのと、全ノードのトラバーサルのしやすさはトレードオフになる気がするよ

**Comment by marihachi** [comment]
他の実装も参考にしたい

**Comment by marihachi** [comment]
JS系のASTとかどんな感じでやってるんだろう

**Comment by marihachi** [comment]
parser/visit.tsを追加した。一応解決したような感じがある？
