### ISSUE TITLE
Attrの記法の変更

### ISSUE THREAD

**Issue by cwd-k2** [syuilo/aiscript#118]
`+` は他の記号と被ることが多いので変えた方が良いかもしれない

- `+` を使わない
- Statement ではなく GlobalStatement や NamespaceMember に移動する（Statement や Expr と違うレベル）

**Comment by cwd-k2** [comment]
https://misskey.io/notes/8orxdz1ozd
> ブロック内の定義文にもattr付けたい

**Comment by marihachi** [comment]
`+`の記号だけで識別するのがまずい気がする。カッコで囲むとか？

**Comment by cwd-k2** [comment]
参考

rust の attribute は `#[...]` の形
https://doc.rust-jp.rs/rust-by-example-ja/attribute.html

swift の attribute や kotlin の annotation は `@name(args)` の形
https://docs.swift.org/swift-book/ReferenceManual/Attributes.html
https://kotlinlang.org/docs/annotations.html#constructors

**Comment by syuilo** [comment]
`#[...]`かねえ

`~ ...`というのも考えたけど

**Comment by cwd-k2** [comment]
`#[]` なら構文上の意味を持つ記号が `#`、`$`、`@` くらいなのかなって感じで話が楽にもなりそう？

**Comment by marihachi** [comment]
`#[...]`すき

**Comment by syuilo** [comment]
↑決定
