### ISSUE TITLE
GitHub pages上でplaygroundを提供する

### ISSUE THREAD

**Issue by syuilo** [syuilo/aiscript#119]
んでGitHub Actionsを利用してデプロイする様にし、PRが来た時にその状態のAiScriptを簡単に試せるようにしたい(できるのか？)

**Comment by syuilo** [comment]
👀
https://qiita.com/peaceiris/items/d401f2e5724fdcb0759d

**Comment by marihachi** [comment]
IIHANASI

**Comment by syuilo** [comment]
チャレンジしてみる

**Comment by syuilo** [comment]
peg.jsはESM形式でパーサを生成しないのでviteで読み込めず開発が妨げられることが判明した
なるはやでpeggyに移行したい(peggyはESMで生成できる)

**Comment by syuilo** [comment]
そんな難しくなさそうだったからついでにやる

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/127686485-56c7a27c-50f8-482b-93cb-b7376d3f6b11.png)

**Comment by syuilo** [comment]
GitHub Pagesは１つのリポジトリにつき１つしか持てないからPRごとにサイト生成は無理そう

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/127692393-efa8d7b1-7db0-404c-9ee4-6e367bc7f762.png)
