### ISSUE TITLE
ESMでjestが動かない

### ISSUE THREAD

**Issue by syuilo** [syuilo/aiscript#127]
つまりparser.jsは読み込めない
どうしたもんかね

**Comment by syuilo** [comment]
型定義ファイル用意してあたかもファイルが存在するように見せかけることでエラーは出なくなった
https://github.com/syuilo/aiscript/commit/b7c9670367918bd96185ac107019156c12f28bd7

**Comment by syuilo** [comment]
ただnode.jsがESM形式を読み込むには拡張子を mjs にしないといけない
でも mjs はTypeScriptがサポートしていない
どうしたもんかね

**Comment by syuilo** [comment]
https://github.com/facebook/jest/issues/11453
👀

**Comment by marihachi** [comment]
ESモジュール、発展途上技術というイメージ

**Comment by syuilo** [comment]
https://kulshekhar.github.io/ts-jest/docs/next/guides/esm-support/
👀

**Comment by cwd-k2** [comment]
一度`.js`でESModuleを出力してbabelとかかけるべき？

**Comment by syuilo** [comment]
ほむ

**Comment by syuilo** [comment]
vite(rollup?)がcommonjs読み込めれば無理にESM使う必要ないんだけど
調べてみるか

**Comment by syuilo** [comment]
↑やっぱり動かない

**Comment by syuilo** [comment]
playground破壊したのでテスト復活した

**Comment by syuilo** [comment]
なんかいい感じになってplayground復活した
