### ISSUE TITLE
構文の誤認識を回避する

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#128]

**Comment by marihachi** [comment]
回避策
- 文末のセミコロンを導入する
- 途中で改行できるようにする記号を導入する
- 二項演算をやっぱり括弧ありに戻す

**Comment by marihachi** [comment]
> 途中で改行できるようにする記号を導入する

```
$a <- hoge \
 + piyo
```
みたいな。`\`は仮です

**Comment by marihachi** [comment]
> 中置演算子式をa + b + c + dは認めず(a + b + c + d)のみを認めるっていうのもあり？

うまくいくか分からない
どうだろう

**Comment by cwd-k2** [comment]
- 文として独立させるには「2つ以上の」改行が必要

とかどう？

**Comment by marihachi** [comment]
演算式以外でもわりと起こる一般的な問題なので、
根本的なアプローチが一番聞くと思う

**Comment by marihachi** [comment]
> 文として独立させるには「2つ以上の」改行が必要
コードがバカ長くなっちゃう

**Comment by marihachi** [comment]
> 途中で改行できるようにする記号を導入する
rubyはこの方法っぽいな

**Comment by syuilo** [comment]
↑の方がコード読む人にとっても分かりやすいし良さそう

**Comment by cwd-k2** [comment]
ruby だと
```ruby
# 2 と出力
puts 1 *
2

# 構文エラー
puts 1
* 2

# 2 と出力
puts 1 \
* 2
```

**Comment by marihachi** [comment]
> ↑の方がコード読む人にとっても分かりやすいし良さそう

これ？
https://github.com/syuilo/aiscript/issues/128#issuecomment-890315802

**Comment by syuilo** [comment]
> > ↑の方がコード読む人にとっても分かりやすいし良さそう
> 
> これ？
> [#128 (comment)](https://github.com/syuilo/aiscript/issues/128#issuecomment-890315802)

それ

**Comment by marihachi** [comment]
> 途中で改行できるようにする記号を導入する

これかなあ
文がシンプルに書けそう、文の範囲が見た目から明確。

**Comment by marihachi** [comment]
> > 途中で改行できるようにする記号を導入する
> 
> ```
> $a <- hoge \
>  + piyo
> ```
> みたいな。`\`は仮です。
> 文は基本的に改行できないことにして、
> 改行する場合は専用の記号を置いて改行する。

これでいくか
改行の記号は何にする？

**Comment by syuilo** [comment]
`\` とか `.` かなあ

**Comment by cwd-k2** [comment]
`\` いいと思う

他にも matlab は確か `...` だった

**Comment by syuilo** [comment]
:naruhodo:

**Comment by marihachi** [comment]
`.`はプロパティ参照とかぶるけどすき
`..`はどう？

**Comment by marihachi** [comment]
旧のelseと被るか
旧のelseを1文字の`.`に限定してサポートすると、`..`を採用できる

**Comment by syuilo** [comment]
ピリオド２つっていうのは若干中途半端に思えるから、それなら`...`かなあと思ったけどピリオド３つだと逆に改行するためだけにしては長すぎる気がするからやっぱり`\`かなあとなった

**Comment by syuilo** [comment]
あとピリオドは将来他の構文でも使いたくなりそう(JSのスプレッド構文みたいな)

**Comment by marihachi** [comment]
`_`という選択肢もある。nullと被ってるけど

**Comment by syuilo** [comment]
そういやnullを_と表記するの若干やめたい

**Comment by marihachi** [comment]
```
$a <- hoge \
 + piyo
```

```
$a <- hoge _
 + piyo
```

見た目は後者がすきだな

**Comment by syuilo** [comment]
ピリオドひとつでも、プロパティ参照はスペース許可しないから被ることはなさそう

**Comment by cwd-k2** [comment]
それならピリオド3つでも被らないということもできそう？

**Comment by cwd-k2** [comment]
`...` は「続きがある」感があるとは思う

**Comment by syuilo** [comment]
VB.NETは`_`だった気がする

**Comment by cwd-k2** [comment]
`.` `..` `...` `\` `_` でアンケートとってみる？

**Comment by marihachi** [comment]
LGTM

**Comment by marihachi** [comment]
https://misskey.io/notes/8ov699abj4 
:eyes:

**Comment by cwd-k2** [comment]
投票数そんなにないけど `\` が優勢っぽい

**Comment by syuilo** [comment]
`\`で行くか

**Comment by syuilo** [comment]
まあリリースするまではいくらでも変えられるしとりあえず決めるのは重要

**Comment by marihachi** [comment]
いこう

**Comment by marihachi** [comment]
ちょっとやってみる

**Comment by marihachi** [comment]
文の途中で改行できないようにするというより、
式の途中で改行できないように、かも

**Comment by marihachi** [comment]
基本的に、文やら式やらの途中で改行はできないようにして、
普通は改行したくなりそうな部分は許容するような方針で書いていってる

**Comment by marihachi** [comment]
全ての文や式で改行できないようにすると、矛盾や不都合が多く出てきた。
そのため、仕様としては以下のように適用範囲を絞って追加したい：
- 文と文の間は改行必須
- Infixの途中では改行できず、改行を含めるには`\`で改行文字をエスケープする (エスケープ未実装)

```
#n = 1 + 1
#r = if (n + 1) = 3 yes else no
// ok!

#n = 1 + 1
#r =
  if (n + 1) = 3
    yes
  else
    no
// ok!

#n = 1 + 1
#r =
  if (n +
  1) = 3
    yes
  else
    no
// syntax error! → 改行のエスケープが必要

#n = 1 + 1 #r = if (n + 1) = 3 yes else no
// syntax error! → 文と文の間は改行しなければならない
```

**Comment by marihachi** [comment]
ちょっと考えてみた。

文と文の間には改行が必要なので、
ユーザーは基本的に1行に1つ文を書くことになる。
そのため、意図せずにInfixに干渉することはなくなりそう。

Infixも途中で改行できないので、
ユーザーは、意図せずに
2つの文として認識されるような書き方はしないはず。

**Comment by marihachi** [comment]
間違えた

**Comment by syuilo** [comment]
ＹＯＳＡＳＯＵ

**Comment by marihachi** [comment]
実装終わった
