### ISSUE TITLE
NodeとValueの違い

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#134]
パーサから来たNodeをインタプリタでValueに変換してる場合があるけど、
何か意図があるんだろうか。
Valueに統合できたらしてしまっても良い？

(余談)
そもそもASTの構成も再度よく検討したほうが良いかも知れないけど

**Comment by syuilo** [comment]
> パーサから来たNodeをインタプリタでValueに変換してる場合

なんだっけ、例ある？

**Comment by syuilo** [comment]
あー
`case 'bool': return BOOL(node.value);`
とかか

**Comment by syuilo** [comment]
構文としてのリテラルとメモリ上のデータとしての値は概念的に異なるから分けた感じだったと思う

**Comment by syuilo** [comment]
統合できなくもないけど統合するメリットは特にないように感じる

**Comment by marihachi** [comment]
Nodeはプログラムで、Valueは値って位置付け？

**Comment by syuilo** [comment]
そうそう

**Comment by marihachi** [comment]
解決した
ありがとう
