### ISSUE TITLE
複数のモジュール形式のサポート

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#136]
playgroundではES modulesが扱いやすい
Node.jsではCommonJSが扱いやすい
→ 環境によって必要なモジュール形式が違う

各モジュール形式のファイルをnpmパッケージに含める
- CommonJS
- ES modules
- UMD

**Comment by marihachi** [comment]
UMDいらんかも

**Comment by syuilo** [comment]
CommonJSはレガシーだからサポートしなくても大きな問題はないかもしれない

**Comment by marihachi** [comment]
CommonJSまだまだ使ってる人多そう
Node.jsで一番枯れてるんじゃない？

**Comment by marihachi** [comment]
もうサーバサイドでもESMが主流なのかなあ

**Comment by marihachi** [comment]
いいか
