### ISSUE TITLE
関数の型宣言

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#139]
型推論(#138)をする上で、関数の型宣言があると便利なので追加したい

## 構文案1

関数定義
```
@max(x: num, y: num): num {
  statement
}
```

関数オブジェクト
```
#max = @(x: num, y: num): num {
  statement
}
```

戻り値の型はオプションにして推論しても良さそう。ブロックやif式が返す値の型推論は必要になるので共通化できる。

**Comment by syuilo** [comment]
この宣言はオプションになる？

**Comment by marihachi** [comment]
多分オプションにできる

**Comment by marihachi** [comment]
型の宣言は必要になるまで保留で良いかも
ほとんど推論できそうなため

**Comment by marihachi** [comment]
引数の型は完全には推論できなさそうなので、
もし型指定をオプションにするとなればanyになるかも。

**Comment by marihachi** [comment]
戻り値は(関数の内容にany型変数を含まない限りは)おそらく完全に推論可能なのでオプションにできる。

**Comment by marihachi** [comment]
関数の内容が空の場合はnullを返してる扱いで良いのかな

**Comment by marihachi** [comment]
Strictモードの時のみ、厳密な型宣言を必須にするかも

- #145

**Comment by marihachi** [comment]
宣言できるようになったのでclose
