### ISSUE TITLE
エディション明示構文

### ISSUE THREAD

**Issue by syuilo** [syuilo/aiscript#154]
今後AiScriptがバージョンアップで構文が変わったりしたときの対応を容易にするために、スクリプトの先頭にエディションを明示できる構文を追加する

```
@ 2021
```

とか

**Comment by marihachi** [comment]
仕様はこんな感じだろうか
- バージョン名には`[A-Z0-9_.-]i`に一致する文字が使用できる
- 複数指定された場合は最後の指定が優先される

**Comment by marihachi** [comment]
構文が変わったりするとパースがコケるから、バージョンだけ読むような工夫がいるなあ

**Comment by syuilo** [comment]
> 構文が変わったりするとパースがコケるから、バージョンだけ読むような工夫がいるなあ

普通にホスト側でスクリプトの一行目だけ取り出して読む、というのを想定してた
AiScript側でパースしたりまでする必要ないかも

**Comment by syuilo** [comment]
そう考えると現状でも
```
//@ 2021
```
みたいにコメント構文使えば実現できるな

**Comment by marihachi** [comment]
パーサに1行目のコメントを読み取る関数を生やしてみた

**Comment by marihachi** [comment]
要らないかな
どうだろう、ユーザー側で用意しても良いだろうけど仕様が違ったらあまり良くない気もする

**Comment by syuilo** [comment]
> どうだろう、ユーザー側で用意しても良いだろうけど仕様が違ったらあまり良くない気もする

たしかに

**Comment by marihachi** [comment]
ユーティリティって感じで関数を公開するか
