### ISSUE TITLE
言語の基本的なコンセプト

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#16]
言語のコンセプト、方向性を固めたい

## ターゲットプラットフォーム
- [x] Node.js環境
- [x] ブラウザ環境

## 型のサポート
- [ ] 全て暗黙的な型

たとえば、もし言語機能としてジェネリックや複合的な型をサポートしたくなったとして、
もはや「全て暗黙的な型」ではなくなる。
明示的な型のサポートが必要となることが予想されるならば始めから明示的に型をつけるようにすべきだと思う。

- [ ] 全て明示的な型 or 明示的な型+暗黙的な型

ぜんぶ明示的だよ。
型を明示する手間はあるけど、その代わりに制約やインタプリタに対して説明を与えることができる。

**Comment by syuilo** [comment]
AiScriptはMisskeyクライアントでも使う予定なのでブラウザでも動作させるのは確定してる

**Comment by syuilo** [comment]
型注釈は無しで良いと思う
スクリプト言語だから手軽に書けた方が良いし、そもそも型推論とか実装するのきつい
ただ将来的に気が変わった時に対応できるような余地を残しておくのは良いと思う
