### ISSUE TITLE
#, $ をキーワードにする？

### ISSUE THREAD

**Issue by syuilo** [syuilo/aiscript#171]
- キーワードの方が分かりやすそう
- 属性構文でも#が使われていて若干紛らわしい
- 記号は数が限られていて貴重なので将来のために予約しておきたい

参考

| 言語 | ミュータブル | イミュータブル |
| ---- | ---- | ---- |
| JavaScript | let | const |
| Rust | let mut | let |
| Swift | var | let |
| Kotlin | var | val |
| Lua | local | local \<const> |
| Go | var | なし？ |
| Python | (暗黙的) | なし？ |

そもそもイミュータブルな変数が必要かどうかも含めて検討したい

**Comment by syuilo** [comment]
個人的にはSwiftスタイルが好きかも

**Comment by marihachi** [comment]
var const が好きかも
言葉が対になってる感じがする

**Comment by syuilo** [comment]
constだと、値そのものがイミュータブルな印象を与える気がしてる
ここでのイミュータブルは参照がイミュータブルってだけだし

**Comment by marihachi** [comment]
var、fix varとかどうだろう

**Comment by marihachi** [comment]
参照先固定の変数みたいな

**Comment by marihachi** [comment]
var、let 良いかも
