### ISSUE TITLE
小数リテラル

### ISSUE THREAD

**Issue by syuilo** [syuilo/aiscript#172]
欲しい

**Comment by cwd-k2** [comment]
最も簡単には
```
[+-]? 整数部 "." 小数部
整数部 => 整数と同様
小数部 => [0-9]+
```
って実装ができると思うけど、`.123`, `1.`, `1.23e+4` みたいな形式のサポートはする？

**Comment by syuilo** [comment]
> `.123`, `1.`, `1.23e+4` みたいな形式のサポートはする？

とりあえずしなくて良さそう
