### ISSUE TITLE
FizzBuzz example gives syntax error

### ISSUE THREAD

**Issue by ThatOneCalculator** [syuilo/aiscript#178]
From the readme: 
> ```
> for (#i, 100) {
>   <: if (i % 15 == 0) "FizzBuzz"
>     elif (i % 3 == 0) "Fizz"
>     elif (i % 5 == 0) "Buzz"
>     else i
> }
> ```

gives
![image](https://user-images.githubusercontent.com/44733677/169609895-90d09dfd-648e-4ba6-8166-c093b0f34c57.png)

**Comment by syuilo** [comment]
Misskey uses the old AiScript.
