### ISSUE TITLE
空ブロックと空オブジェクト式の干渉

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#181]
#179 の無名関数`() => {}`を実現する上での問題点についての検討。
空ブロックと空オブジェクト式が干渉してしまう。

## 関係する要件・仕様
- 代入式でブロックが使える
- 代入式でオブジェクト式が使える
- 代入式で`{}`を渡した場合はオブジェクト式と解釈する
- 無名関数でブロックが使える
- 無名関数でオブジェクト式が使える。 その場合は`({})`と指定する。
- 無名関数で`{}`を返した場合はブロックと解釈する

## 懸念
- 対象によって式の優先度が変わるのはユーザーにとっても優しくなさそう。

**Comment by marihachi** [comment]
ブロックとブロック式の構文を分けるのはどうかな
ブロック: `{}`
ブロック式: ?

**Comment by syuilo** [comment]
> ブロック式

```
let result = do {
  1 + 2
}
```
みたいなのどうじゃろ

**Comment by marihachi** [comment]
doはdo-whileから繰り返しのイメージがあるような

**Comment by marihachi** [comment]
scope とかでも良いような

**Comment by marihachi** [comment]
```
let result = scope {
  let x = calc(2)
  let a = calc(1)
  2 * x + a
}
```

**Comment by marihachi** [comment]
名詞じゃないほうが良いのかな

**Comment by syuilo** [comment]
`eval`とか`exec`とかでも良さそう
```
let result = ${
  let x = calc(2)
  let a = calc(1)
  2 * x + a
}
```
みたいに記号使うのも良さそう

**Comment by marihachi** [comment]
Linqみたいに`from` とかどうだろう
```
let result = from {
  let x = calc(2)
  let a = calc(1)
  2 * x + a
}
```

**Comment by syuilo** [comment]
ほむん
from はあまり馴染みなかった

**Comment by marihachi** [comment]
記号は何の記号だったか忘れるかも
初見だと意味を把握しづらいかも

**Comment by syuilo** [comment]
`${}`はテンプレート文字列でも使われる構文だからその点は分かりやすいと思った

**Comment by marihachi** [comment]
> evalとかexecとかでも良さそう 
この2つは普通にアリ

**Comment by marihachi** [comment]
fromは、続くブロック**から**その式の値を評価するって意味で良いかなと思った

**Comment by marihachi** [comment]
個人的には
1位 from
2位 eval
って感じかも

**Comment by marihachi** [comment]
あとは他の人の意見も参考にしたい感じ

**Comment by marihachi** [comment]
遅延評価とかも考えると、evalの方が良いのかな

**Comment by marihachi** [comment]
仮に遅延評価を、
```
lazy { }
```
とかにする場合に、即時評価を
```
eval { }
```
とするのは自然な気がする

**Comment by syuilo** [comment]
evalにするか

**Comment by marihachi** [comment]
eval式追加してみるか

**Comment by marihachi** [comment]
eval式を追加すると、ブロック文(文`{}`)があまり要らなくなるかも。
ブロック文は値を返せないため、スコープが生成されるだけの構文になる。

**Comment by marihachi** [comment]
ブロックを触ってmatch式にも影響が出てるな

**Comment by marihachi** [comment]
解決策1ダメかも
ブロック文はmatchなどの構文の一部としてごく一般的に使用されてる。
これを変えると、ちょっと整合しなくなるな...

**Comment by marihachi** [comment]
## 解決策2
- ブロックを式ではなく文に変更
- ブロック式の代替としてeval式を追加

こうかも

**Comment by marihachi** [comment]
matchでstatementを取るようにすれば良いかも？

**Comment by marihachi** [comment]
何も分からなくなってきた

**Comment by marihachi** [comment]
## 解決策2
- 無名関数やmatchなどで文を取るようにする

これだけでいいかも

**Comment by marihachi** [comment]
- ブロックが式である限りはオブジェクト式と干渉する
- ブロックが式でなければifやmatchで値を返すことができない

詰んできた

**Comment by marihachi** [comment]
ifやmatchの構文を変更してブロックを使わないようにすれば何とかなるかもしれないけど、あまり美しくはないな

**Comment by syuilo** [comment]
> ブロックが式でなければifやmatchでブロックを用いて値を返すことができない

これどういうこと？

**Comment by syuilo** [comment]
例えば
```
<: match 2 {
	1 => "a"
	2 => "b"
	3 => "c"
}
```
のような一般的なコードは今回の変更に影響されない気がした

**Comment by marihachi** [comment]
ブロックを文に変更するとして、
`=>`の右側は式を受け取ってるけど、ここで文を受け取るようにする必要があると思う。
ただ、文に値を返す機能はない(と現状ぼくは思っている)ためダメだと思った。

**Comment by syuilo** [comment]
> =>の右側は式を受け取ってるけど、ここで文を受け取るようにする必要があると思う。

これはなぜ？

**Comment by marihachi** [comment]
ブロックが文になるから

**Comment by syuilo** [comment]
ブロック関係なくない？

**Comment by marihachi** [comment]
https://github.com/syuilo/aiscript/blob/master/src/parser/parser.peggy#L382 
ここで式を受け取ってて、
```
<: match 2 {
	1 =>  {
		"a"
	}
	2 => {
		"b"
	}
	3 =>  {
		"c"
	}
}
```
をしたい場合にブロックの式が使われると思うけど...

**Comment by syuilo** [comment]
> https://github.com/syuilo/aiscript/blob/master/src/parser/parser.peggy#L382 ここで式を受け取ってて、
> 
> ```
> <: match 2 {
> 	1 =>  {
> 		"a"
> 	}
> 	2 => {
> 		"b"
> 	}
> 	3 =>  {
> 		"c"
> 	}
> }
> ```
> 
> をしたい場合にブロックの式が使われると思うけど...

この場合は

```
<: match 2 {
	1 =>  eval {
		"a"
	}
	2 => eval {
		"b"
	}
	3 =>  eval {
		"c"
	}
}
```

と書くようになると思ってた

**Comment by marihachi** [comment]
それなら可能だけど、見た目が微妙じゃない？
```
if true eval { } else eval {  }
```
とかになる

**Comment by syuilo** [comment]
あー
matchに関して言えば、ブロック式が使われることはあまりないと思うから
```
<: match 2 {
	1 =>  eval {
		"a"
	}
	2 => eval {
		"b"
	}
	3 =>  eval {
		"c"
	}
}
```
で良いと思ってたけど、if はなあ

**Comment by syuilo** [comment]
「ifは式である」というのを一旦やめる(=ブロック必須にする)とか
やめた後でやっぱり欲しくなったらif文とは別に三項演算子的な構文を設けるとか

**Comment by marihachi** [comment]
> ifやmatchの構文を変更してブロックを使わないようにすれば何とかなるかもしれないけど、あまり美しくはないな

これをするか
そもそも構文として、その部分が「ブロック式」とは別物の構文であることにすれば解決するかも

**Comment by marihachi** [comment]
こんな感じで
```
ifContent = Expr / "{" Statements "}"
```

**Comment by marihachi** [comment]
オブジェクト式の構文を変更したら解決する感じがしてきた

**Comment by syuilo** [comment]
それできたら一番楽なんだけど、JSONをそのまま解釈したいという思いがある

**Comment by marihachi** [comment]
ブロックを文に変更して、
ブロック文は値を返せることにするとか

**Comment by syuilo** [comment]
良いかも

**Comment by marihachi** [comment]
文が値を返すのを良しとするかって話にはなるけど

**Comment by syuilo** [comment]
> そもそも構文として、その部分が「ブロック式」とは別物の構文であることにすれば解決するかも

これで良さそう

**Comment by marihachi** [comment]
## 解決策2
- オブジェクト式は現状維持
- ブロック式を廃止し代わりにeval式を追加
- 構文規則にブロック`{}`を直接追加 (ifやmatch、無名関数、他...)
- 代入式ではブロックではなくeval式を使用する

## 関係する要件
- [x] 代入式で~~ブロックが使える~~ eval式が使える
- [x] 代入式でオブジェクト式が使える
- [x] 代入式で`{}`を渡した場合はオブジェクト式と解釈する
- [x] 無名関数でブロックが使える
- [x] 無名関数でオブジェクト式が使える。 その場合は`({})`と指定する。
- [x] 無名関数で`{}`を返した場合はブロックと解釈する

まとめた
こんな感じかな

**Comment by syuilo** [comment]
👍🏻👍🏻

**Comment by marihachi** [comment]
実際の作業についてのissueを立てたのでcloseします

**Comment by lemoncmd** [comment]
これ、空ブロックの戻り値を空オブジェクトにすることで解決できませんか。

**Comment by saki-lere** [comment]
> これ、空ブロックの戻り値を空オブジェクトにすることで解決できませんか。

空ブロックからはnullが返ってほしい気がする。
