### ISSUE TITLE
プロパティ参照やインデックス参照、関数コールなどをより柔軟に組み合わせられるように

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#194]
現状のパーサーでは、プロパティ名(プロパティパス)を指定して関数コールや変数の参照を行えるが、
それら(関数コールやインデックス、変数参照)を組み合わせて指定することはできない。
より柔軟に、それらを組み合わせられるようにしたい。

パーサーが返すASTが変更になることが予想されるので、インタプリタも変更になる。

- [ ] パーサーの変更 (#196) 
- [ ] ノード定義の変更 (#196) 
- [ ] 各種プラグインの変更 (#196) 
- [ ] infix-to-fncallの変更 (#196) 
- [ ] インタプリタの変更 (#199)

**Comment by marihachi** [comment]
https://github.com/syuilo/aiscript/blob/work/refactor-2/src/parser/parser.peggy 
まだASTの加工は必要だけど、とりあえずパースはできてる様子

**Comment by marihachi** [comment]
チェーン周りのノードの設計をした。

```
abc().prop1.prop2
```
というチェーンがある時、
```ts
{
  type: 'prop',
  name: 'prop2',
  expr: {
    type: 'prop',
    name: 'prop1',
    expr: {
      type: 'call',
      args: [],
      expr: {
        type: 'var',
        name: 'abc'
      }
    }
  }
}
```
のようなIRノードが生成される予定。

**Comment by syuilo** [comment]
done
