### ISSUE TITLE
シリアライザの見直しまたは廃止

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#197]
シリアライズ後のデータは文字列が良さそう

そもそもシリアライザが必要かどうかという検討も必要そう
この機能はどういう時に使うんだろう？ソースコードでは問題がある？

わりとメンテナンスが大変で、メリットが少ないのであれば廃止したい

**Comment by syuilo** [comment]
廃止しようぜ

**Comment by syuilo** [comment]
AiScriptで書かれたプログラムを扱うときにソースコードでしか永続化手段が無いとコメントや空行など実行時には必要のない情報まで保存しなければならず無駄かと思って作った

**Comment by marihachi** [comment]
> AiScriptで書かれたプログラムを扱うときにソースコードでしか永続化手段が無いとコメントや空行など実行時には必要のない情報まで保存しなければならず無駄かと思って作った

この問題は実際にはあると思うけど、インタプリタでソースコードを直接実行するという範囲であればソースコードで十分な感じがする。
