### ISSUE TITLE
import type構文は何のために使用する？

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#218]
lintのルールでimport typeを使用することになったけど、
これは何のため？

TypeScriptのドキュメントによると、ほとんどの人はこれを気にする必要がないとあった。
明示的にこれを使用する理由はなんですか。

メリットがあれば教えて下さい。

**Comment by syuilo** [comment]
ファイルの依存関係を把握するときに、importを見ると思うんだけどその時に単に型だけに依存してるのかロジックに依存してるのか分かりやすくなるとか

参考:
https://scrapbox.io/tascript/%E3%80%8CType-Only_Imports_and_Export%E3%80%8D%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E8%89%B2%E3%80%85%E3%81%A8%E8%80%83%E3%81%88%E3%81%A6%E3%81%BF%E3%82%8B

個人的にはclassのフィールドにpublicとか明示するようにするのと同じ感じだと思ってる
