### ISSUE TITLE
二項演算の式で符号付きの数値を使うとパースに失敗する

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#220]
## 入力例
```
let a = 1*-2
```

## 原因
`*-`として演算子がマッチしてしまう

## 回避策
かっこを付ける、またはスペースを開ける
```
let a = 1*(-2)

let a = 1* -2
```

**Comment by FineArchs** [comment]
[パーサーの演算子部分](https://github.com/syuilo/aiscript/blob/8ccb62ecce8d428d217289ca756a3e4d26f05db4/src/parser/parser.peggy#L325-L327)
```
Op
	= ("||" / "&&" / "==" / "!=" / "<=" / ">=" / "<" / ">" / "+" / "-" / "*" / "^" / "/" / "%") ![-+*^/%&|=~<>!?]
{ return text(); }
```
の`![-+*^/%&|=~<>!?]`の部分を除去すれば問題なく動作するようです。

必要ないものであれば除去してしまいたいのですが、どうでしょうか？
