### ISSUE TITLE
`Arr:`で始まる組み込み関数が消えていて動かない

### ISSUE THREAD

**Issue by futchitwo** [syuilo/aiscript#226]
https://github.com/syuilo/aiscript/blob/b4ebc37e3fca094c577955ed6ffbcf7a655fb2a1/src/interpreter/lib/std.ts#L266-L267

仕様: https://github.com/syuilo/aiscript/blob/master/docs/std.md

**Comment by syuilo** [comment]
`[1 2 3].len`みたいに書くようになったからドキュメントの方が誤ってる
