### ISSUE TITLE
関数呼び出しのパースの改善

### ISSUE THREAD

**Issue by syuilo** [syuilo/aiscript#23]
現在は
name:NAME "(" _ args:fnCall_args? _ ")"
になってるけど
fn:expression "(" _ args:fnCall_args? _ ")"
にしないとダメ
でもそうすると左再帰になりそう

**Comment by marihachi** [comment]
何をするために、そうしないといけないの

**Comment by marihachi** [comment]
#25 の話？

**Comment by syuilo** [comment]
それもあるね
あとJSだと
``` js
(() => { hoge })()
```
みたいにも書ける

**Comment by marihachi** [comment]
```(() => { hoge })```が関数オブジェクトを返す式だと考えれば、#25のやり方でできそう

**Comment by marihachi** [comment]
Resolved by #196
