### ISSUE TITLE
v0.12.4にて数式などが名前空間の定義内では関数呼び出しに変換されない

### ISSUE THREAD

**Issue by ikasoba** [syuilo/aiscript#238]
## 起こること
`Error: invalid node type`というエラーが起こる

## その現象を再現するコード
```
:: Hoge {
  @add(x, y) {
    x + y
  }
}
Hoge:add(1 2)
```

## 考えられる原因
./src/parser/visit.tsのvisitNodeにNamespace用の実装が無くてこのような現象が起きているようです。

**Comment by ikasoba** [comment]
バグであるならアサインしていただければプルリクエストを作成します。

**Comment by syuilo** [comment]
お願いします🙏
