### ISSUE TITLE
Ability to sort arrays

### ISSUE THREAD

**Issue by MineCake147E** [syuilo/aiscript#253]
## Summary

I wish I could sort the array.

## API usage

```aiscript
sort(array, @(x, y))   //comparison predicate that returns positive value if x > y, 0 if equal, and negative value if x < y
```

**Comment by tsukimizake** [comment]
I'm currently working on this implementation. Sorting numbers and  sorting objects by field are working. 
As I couldn't find a way to pass the `opts.call` async function to `Array.sort`, for now, I implemented bubble sort by hand. 
I think I'll replace it with quick sort or something.

Considering that JavaScript's default behavior of treating arrays as arrays of strings without a comparison function is harmful, I believe it's better not to bring this behavior into AiScript.
My current thought is, in addition to providing `Arr:sort(arr,@(x,y))`, it might be a good idea to also provide `Str:lt(l,r)` and `Str:gt(l,r)` for string comparator as FN_NATIVE functions.
Is this approach reasonable? I'd like to ask the opinions of senior developers about the API design.

### Japanese summary:
- 実装中です。アルゴリズムは一旦バブルソートですがnumberやobjectのソートが動いています。
- comp関数がない場合stringと見なしてソートするというJSの挙動は変なのでAiScriptに持って行かない方がいいだろうと考えており、今の考えでは、`Arr:sort(arr, @(x, y))` の実装に加えて`Arr<string>`のソート用に `Str:lt(l, r)` と `Str:gt(l, r)` も比較関数として提供してやるのが良いのでは？と考えていますがこの方針で良いでしょうか？

**Comment by saki-lere** [comment]
プロパティの方が一貫性があるかも？
`arr.sort(@(a, b){})`

**Comment by tsukimizake** [comment]
https://qiita.com/saki-lere/items/851c4500d56659d15c9c#0120%E3%81%8B%E3%82%89%E3%81%AE%E7%A0%B4%E5%A3%8A%E7%9A%84%E5%A4%89%E6%9B%B4 たしかに
Arr:sortは primitive-props.ts に移動していきます
