### ISSUE TITLE
Date:now()の値から年月日等を取得できるようにしてほしい

### ISSUE THREAD

**Issue by Dugesia7** [syuilo/aiscript#261]
現状だと年・月・日等を取得するにはDate:year()等で個別に取得する必要がありますが、それぞれでDateオブジェクトを生成しているため厳密に同じ時刻を指さない恐れがあります。
これを回避するために、Date:now()で取得した値を年・月・日等に変換できる手段が欲しいです。よろしくお願いします。

**Comment by taichanNE30** [comment]
これ欲しいので実装したい（強い意志）
