### ISSUE TITLE
breakをreturn nullと同義にするか

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#277]
returnが使われるべき場所（今のところは関数のみ？）でbreakが使われた時、
- return nullとして扱う
- エラーとして扱う
の２つで迷っています。（continueはいずれにしてもエラー？）

**Comment by yuriha-chan** [comment]
breakはループを脱出するという意味だけもたせ、ループの外で使われた場合は構文エラーにするのが妥当だと思います。

return nullと同等ならreturn nullと書けば、制御を関数の呼び出し元に戻すという意図がより明確に表せるはずなので、プログラマーがその挙動を正しく理解しているということを確認するためにもループ外breakはエラーにすべきだと思います。

**Comment by FineArchs** [comment]
確かにその通りですね。ありがとうございます。
