### ISSUE TITLE
JSONへのパース可能性を評価する関数

### ISSUE THREAD

**Issue by zawa-ch** [syuilo/aiscript#282]
`Json:parse(json)`に非JSON文字列を代入して実行した場合の挙動が「エラーを投げて即時そのコンテキストでの実行を終了する」であるため、開発者は文字列をJSONへパースできるかを知ることができません。
JSONへパースできる(=`Json:parse(json)`の実行時にエラーが発生することなく、期待された値を返す)ときに`true`、そうでないときに`false`を返す関数があると助かります:

```
<: Json:is_parsable('["ai", "chan", "kawaii"]') // -> true
<: Json:is_parsable('hoge') // -> false
```

現行では次の方法で簡易的に実装することができます。
ただ、この実装は正しいJSONでも一部のケースで`false`を返す可能性があります:

```
/// @ 0.13.3
@is_parsable_to_json(json_str) {
  var result = null
  let t1 = Async:timeout(100, @() { if Core:type(result) == 'null' { result = false } })
  let t2 = Async:timeout(0, @() {
    Json:parse(json_str)
    result = true
  })
  loop { if Core:type(result) != 'null' { break } }
  t1()
  t2()
  result
}

let correct_json = '["ai", "chan", "kawaii"]'
let illegal_json = 'hoge'

<: is_parsable_to_json(correct_json) // -> true
<: is_parsable_to_json(illegal_json) // -> false
```

**Comment by FineArchs** [comment]
`Json_parse(json)`を失敗したときにエラーを吐くのではなくnullを返すとかでもよさそうですかね？

**Comment by zawa-ch** [comment]
`Json:parse(json)` に失敗したときに `null` を返すようにしてしまうと、パースに失敗して `null` になったのか、 `'null'` をパースした結果として `null` になったのかがわからなくなってしまう懸念があります

**Comment by FineArchs** [comment]
確かに・・・
ではその方向でやってみます。（今は@syuilo さんがMisskeyの最適化で忙しそうなので反映されるのはかなり先になるかもしれません）

**Comment by syuilo** [comment]
理想的にはtry~catchのような例外処理機構を実装するか、null以外の何かを返してパースに失敗したことが分かればいいんだけど、時間かかるからとりあえず「JSONへのパース可能性を評価する関数」の実装でお茶を濁すか
