### ISSUE TITLE
現在閲覧中のURLを取得する方法が欲しい

### ISSUE THREAD

**Issue by setaria430** [syuilo/aiscript#287]
AiScriptでウィジェットやプラグインを作っていると、URLを取得したい場面がよくあります
（自分で `window.location.href` のラッパーを書こうかと思ったのですが、std.tsという感じではないですし、現存するinterpreterとだいぶ毛色も異なるので、お伺いを立てるに至りました。）
もしあると以下のようなケースでとても役に立つと思っております
- URLに`/channels/`を含む場合、ノート投稿時に確認ダイアログを出せる（チャンネル投稿を公開タイムラインに誤爆する人が非常に多いため）
- URLに`/antenna/`を含む場合、別ドメインのノートを非表示にできる（Misskey自体の機能であればベターですが、プラグインでも可能だと思っています）
- その他、特定のチャンネル・アンテナでのみプラグインを動作させる
- ドメインをソースにベタ書きしなくて済む

…等々 URLを条件分岐の判定に使えると自由度がグッと広がると思いますので、ご一考よろしくお願い致します。

**Comment by FineArchs** [comment]
PlayでいうTHIS_URLをウィジェットやプラグインからも使えるようにする感じですね。
Misskeyの機能や情報、UIなどにアクセスする系の機能は[Misskeyの方](https://github.com/misskey-dev/misskey/tree/develop/packages/frontend/src/scripts/aiscript)に実装されているはずですので、そちらにお願いします。

**Comment by syuilo** [comment]
AiScriptがURLという概念のある環境上で実行されるとは限らない(node.jsなど)ので、Misskey側に実装することになります🙏
