### ISSUE TITLE
関係のない変数が上書きできてしまうバグ？

### ISSUE THREAD

**Issue by ikasoba** [syuilo/aiscript#290]
addAssign, subAssignで関数越しに変数が上書きできてしまうバグらしきものを発見しましたので報告と修正の Pull Request を送らせていただきます。

```aiscript
var hoge = 1

@func(value) {
  value += 1
}

func(hoge)

<: hoge // 2になっている
```

もし仕様であれば閉じてしまって構いません。m(_ _)m

**Comment by saki-lere** [comment]
現状は「`a = a + b`だと新しい値が作られるけど`a += b`はaの中身を書き換える」になってて
`a = a + b`と同じにするべきかどうか、ということかな

**Comment by ikasoba** [comment]
そうです( ´∀｀)
