### ISSUE TITLE
変数の存在の有無を判定する構文の提供

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#297]
特定の変数、その他配列やオブジェクトの要素などが存在しているかをエラーを出さずに判定できる手段を提供したいと考えています。
通常の関数の形にするのは難しいので、新しく構文を作りたいです。
```
exists 変数名
```
以上のようなものを考えていますが、問題ないでしょうか？

**Comment by syuilo** [comment]
「変数の存在を判定したいケース」ってどんなものがありますか？

**Comment by saki-lere** [comment]
Pythonの`locals`みたいのがあったら楽しそう

**Comment by FineArchs** [comment]
@syuilo 
Misskey Playでの例ですが、`THIS_URL`を使用しているPlayのデバッグをScratchpadでやれるようにしたい場面があります。

**Comment by syuilo** [comment]
LGTM

**Comment by FineArchs** [comment]
@saki-lere そういうを用意してObj:has()で判定させる手もありますね・・・

**Comment by syuilo** [comment]
まあMisskey Playの例について言うと IS_PLAY みたいな変数を用意して判定させた方がスマートそう

**Comment by FineArchs** [comment]
@saki-lere 言われてみればそれでダメな理由がないですね・・・

**Comment by FineArchs** [comment]
最初は配列やオブジェクトの要素の存在確認もできるようにするつもりだったのでExprを直接受け付ける必要があったのですが、現行の#298 だと面倒になってIdentifierしか受け付けなくしたので文字列渡しでダメな理由がなくなっています

というわけで`Core:exists("変数名")`として実装する方向に転換したいと思いますが、`exists 〇〇`は当初の予定どおり配列やオブジェクトの要素の存在確認もする構文として作り直すかもしれません。

**Comment by FineArchs** [comment]
> @saki-lere 言われてみればそれでダメな理由がないですね・・・



> 最初は配列やオブジェクトの要素の存在確認もできるようにするつもりだったのでExprを直接受け付ける必要があったのですが、現行の#298 だと面倒になってIdentifierしか受け付けなくしたので文字列渡しでダメな理由がなくなっています
> 
> というわけで`Core:exists("変数名")`として実装する方向に転換したいと思いますが、`exists 〇〇`は当初の予定どおり配列やオブジェクトの要素の存在確認もする構文として作り直すかもしれません。

と思ってたんですけどscope周りの処理が思ったより面倒くさいのでやっぱり構文で実装じゃダメですか？

**Comment by saki-lere** [comment]
scope周りの処理というと？

**Comment by FineArchs** [comment]
std関数からスコープ内の変数のリストを取得するために、`Interpreter._fn`の引数を増やして呼び出し側から`Scope`を受け取る必要があるのですが、`Interpreter._fn`の`Interpreter.eval`以外の呼び出し手（Async系std関数、`Interpreter.execFn`インターフェース）がどんなscopeを渡せばいいのかが分からないです。
