### ISSUE TITLE
npm startを廃止する

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#300]
現状run.jsとparse.jsは古くなっている上に、最新版に書き直してもCommonJS・ESModulesのしがらみで動作させるのが非常に困難になっています。
紛らわしいので削除してしまったほうがいいのではないでしょうか？

**Comment by syuilo** [comment]
> CommonJS・ESModulesのしがらみで動作させるのが非常に困難

そんなことはない気がしている

ただめんどくさいのは事実だから消すかしら

**Comment by FineArchs** [comment]
package.jsonに`"type": "module"`を追加して、import文のパスに拡張子(`.js`)を追加して、autobind-decoratorのソースを直接追加すれば一応動きはするようですが、jestが動かなくなるっぽいです

**Comment by FineArchs** [comment]
#316 で修復したためcloseします。
