### ISSUE TITLE
aiscriptをnodeからimportできない

### ISSUE THREAD

**Issue by ikasoba** [syuilo/aiscript#308]
# 起こっていること
aiscriptはバンドラーなしではnodeから利用することができないっぽいです。

# 原因
- ビルド後のファイルが `esmodule` で書かれているが、 `package.json` の設定では `commonjs` になっていて、nodeから `commonjs` のパッケージとして認識されてしまう。
- import文の拡張子が省略されているので純粋な `esmodule` の環境では読み込みができない。

**Comment by FineArchs** [comment]
やっぱりesmodule化した方がよさそうですかね？

**Comment by ikasoba** [comment]
ローカルのmisskeyで全てのimportに拡張子付けたesmとcjsに対応したバージョンを試したらうまく行ったのでPR出そうかな

**Comment by FineArchs** [comment]
確か普通にやるとautobind-decoratorとjestがうまく動かない問題があった気がするんですけど、大丈夫でした？

**Comment by ikasoba** [comment]
今絶賛格闘中です、jestは動かせたんですけどautobindがあれですね

**Comment by ikasoba** [comment]
原因がわからん...。一応読み込めてるっぽいんだよな

**Comment by FineArchs** [comment]
https://github.com/misskey-dev/misskey/blob/develop/packages/backend/src/decorators.ts
misskeyの方だと改造して使ってるっぽいですね

**Comment by ikasoba** [comment]
知見

**Comment by ikasoba** [comment]
なんでautobindがtestで引っかかる理由がわかった！！！
jestがcommonjsとして解釈してるからだ！！！！

**Comment by ikasoba** [comment]
もしかしたらjestでnative esmなコードを実行できたらテスト通るようにできそうかも

**Comment by ikasoba** [comment]
うーん、commonjsとesmoduleを混在させてるからあんまり良くない感じになってるかも
ビルド後のファイルを見にいったらcjsじゃ動かなさそうなコード生成されてた。(それはそう)
作るほうが楽そうなまである

**Comment by ikasoba** [comment]
PR出してきた

**Comment by ikasoba** [comment]
マージされたので閉じ
