### ISSUE TITLE
名前空間内で定義した変数を外部からでも変更できるように

### ISSUE THREAD

**Issue by ikasoba** [syuilo/aiscript#311]
# 起きていること

現状では、名前空間内にある`var`で定義した変数は外部から変更した際に、名前空間のスコープに生えている変数とは同期がされないようです。
```js
:: Hoge {
  var fuga = 1234

  @increment_fuga() {
    fuga += 1
  }

  @print_fuga() {
    <: fuga
  }
}

Hoge:fuga = 5678

// 1234のまま
Hoge:print_fuga()

// 5678と表示される
<: Hoge:fuga

Hoge:increment_fuga()

// 1235が表示される
Hoge:print_fuga()
```

# 提案

- 名前空間内で定義した変数を外部からでも変更できるようにする

**Comment by ikasoba** [comment]
これやるならどうしてもスコープの動きを上書きしなきゃだけどむつかしいな

**Comment by ikasoba** [comment]
上書きしても現在の実装だと親のスコープの挙動が上書きされているとしても子のスコープからは何の影響も無くなってしまうからScopeの実装をすこし変える必要がありそう

**Comment by ikasoba** [comment]
PR書こうかな

**Comment by syuilo** [comment]
確認遅れて申し訳ない
名前空間にある変数を変更したいケースってどんなのがありそう？

**Comment by FineArchs** [comment]
ユースケースはパッとは思いつかないけど、現状の挙動が異常なのでそれを放置するよりはマージしたい気持ちがあります

**Comment by syuilo** [comment]
制限を後から弱めるのは簡単だけど制限を後から強めるのは困難だから、安易に挙動変更はしにくい
特にユースケースがなさそうなら名前空間内の変数はreadonlyで変更はできないようにした方がいいかも

**Comment by FineArchs** [comment]
それはそう
ただletを差し置いてこっちだけ変更不能にするのは一貫性がない気がします

**Comment by syuilo** [comment]
letが変更可能になっているのを修正する+名前空間内ではletしか使えないようにする
をするしかないか

**Comment by ikasoba** [comment]
> 確認遅れて申し訳ない 名前空間にある変数を変更したいケースってどんなのがありそう？

ぱっと思いつきにくいですね。
ですが、namespace内で変数が変更がされた場合も同様に外部から変数を読む際に初期化時の値のままなのでそこがちょっと気になりますね

**Comment by FineArchs** [comment]
> letが変更可能になっているのを修正する+名前空間内ではletしか使えないようにする
をするしかないか

全部letになるならそもそもnamespace内でも値は変更できないことに…？

**Comment by syuilo** [comment]
yes

**Comment by FineArchs** [comment]
うーん　まあ確かに名前空間というのは本来そういうものではありますね（stdで提供しているものも全て定数か関数ですし）
内部に値を持って色々やるのはオブジェクトとかモジュールに近いですね

**Comment by ikasoba** [comment]
そうかもしれない

**Comment by ikasoba** [comment]
このissueどうしましょう、名前空間内の変数はletのみにする方針で行きます？
そうするなら新しく建てたほうが良いかな:thinking:

**Comment by syuilo** [comment]
👍
