### ISSUE TITLE
Async:関数のコールバック内のエラーを処理する手段がない

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#318]
現在、Async:関数に渡した関数内でaiscript errorが発生しても、通常のようにエラーダイアログが表示されません。
（これはMisskey PlayのMk:button等のイベントコールバックにも同様のことが言えます。）

言い換えれば、`opts.call`を通じてInterpreter外の主体から呼び出される関数のエラーはInterpreter.execを囲うtry-catch構文に引っ掛かりません。

**Comment by ikasoba** [comment]
コードの評価中に生成されたPromiseはどこかに保持しておいて、評価が終わった時にまだ処理中のPromiseがあるならawaitしたりしたら良さそうかな🤔

**Comment by ikasoba** [comment]
それだとイベント発火時のハンドラーで起きたエラーはキャッチできないな

**Comment by FineArchs** [comment]
Interpreterにエラー処理用のコールバックを渡せるようにする？inとかoutみたいな感じで

**Comment by ikasoba** [comment]
それ良さそうかも(\*´ω｀\*)

**Comment by FineArchs** [comment]
とりあえず
>Interpreterにエラー処理用のコールバックを渡せるようにする？inとかoutみたいな感じで

の方向性でやってみます

**Comment by FineArchs** [comment]
経過レポート：

「`Interpreter.exec`（通常の実行）と`opts.call`双方の実行部分をtry-catchで囲み、引っ掛かったエラーが`AiScriptError`なら`Interpreter.exec.abort`により実行停止後に登録されているエラーコールバックを実行（再throwはしない）、それ以外なら再throw」
という形で実装を試みる。
`AiScriptError`発生時に再throwを行わないため`opts.call`の呼び出し元が停止せず、それによる想定外の挙動の懸念あり。

**Comment by FineArchs** [comment]
opts.call実行中にAiScriptErrorが発生したら
・エラーが発生したことを示す値を返す？
・独自のエラーをthrowする？
いずれにせよopts.callの呼び出し元さんにはopts.callが失敗した時の挙動を考えてもらう必要がありそう

**Comment by FineArchs** [comment]
opts.callでエラーをキャッチしたらエラーコールバックを呼び出す
→array.mapに渡された関数が失敗した時エラーコールバックが複数回呼び出されてしまう

これがどうにもならない

**Comment by FineArchs** [comment]
もう普通にエラーコールバックを呼び出すopts.callと呼び出さないopts.callに分けたほうがいいかもしれない

**Comment by FineArchs** [comment]
jsの関数の実行を外部から中断する手段があれば…

**Comment by ikasoba** [comment]
aiscriptの`arr#map`の実装はforループじゃなくてJSの`Array#map`で処理してから`Promise.all`でPromiseを待つっぽいから実装を変える必要がありそう？

**Comment by FineArchs** [comment]
順次実行ならforかeachでいいのでは？という気がするので、出来ればmapの個性たる非同期実行は消したくない気持ちがある
>もう普通にエラーコールバックを呼び出すopts.callと呼び出さないopts.callに分けたほうがいいかもしれない

これでエラーコールバックしないopts.callを渡して結果に一個でもエラーが含まれればエラーコールバックする、みたいなやり方もあるし

**Comment by FineArchs** [comment]
コールスタック上位にopts.call（またはその中身であるInterpreter._fn）がない場合のみエラーコールバックを実行、みたいなことがもし出来ればそれが一番スマートではあると思う
