### ISSUE TITLE
this キーワードを追加

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#319]
関数がオブジェクトの要素である時、関数内で親オブジェクトを参照できるキーワード（this）が欲しいという話が耳に入ったのでissueにします。

**Comment by syuilo** [comment]
これやるとJSの悪夢が蘇りそうなので普通にクラスを実装した方が良さそう

**Comment by FineArchs** [comment]
それはそうですね…

**Comment by FineArchs** [comment]
#66
