### ISSUE TITLE
letで定義した変数が変更できてしまう

### ISSUE THREAD

**Issue by ikasoba** [syuilo/aiscript#328]
#311 から作成

# 起きていること
letで定義した変数が変更できてしまう
```ts
let hoge = 1234
<: hoge
hoge = 5678
<: hoge
```

# 提案
- letで定義した変数へ値を代入しようとしたときにランタイムエラーを発生させる

**Comment by ikasoba** [comment]
不変かどうか管理するために、変数オブジェクトを作ってそれをScope内に収納する形で実装しようかな

**Comment by FineArchs** [comment]
変数オブジェクトというのは変数名と変数の付加情報（constかどうかなど）の対応表的なもの？

**Comment by ikasoba** [comment]
> 変数オブジェクトというのは変数名と変数の付加情報（constかどうかなど）の対応表的なもの？

そうです

**Comment by ikasoba** [comment]
対応表というよりもラベル付けに親しいかもしれないです

**Comment by FineArchs** [comment]
なるほど…
自分は変数の情報は変数自体に付加しちゃってもいいかなと思ってましたが、まあどっちでもいいか

**Comment by marihachi** [comment]
これって元々、変更できないようにはしてなかったような
だからバグではなさそう

**Comment by ikasoba** [comment]
そうだったのか(；・∀・)
当時はどんな考えで実装されてたんだろう:thinking:

**Comment by saki-lere** [comment]
パフォーマンスを考慮してただの意思表示に留めたとのこと
