### ISSUE TITLE
質問：cjs対応を削除したのは何故？

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#339]
https://github.com/syuilo/aiscript/commit/73b42261c30a8fd0a61cda0c35244ec7be205fa9
でCommonJS版を出力する機能が削除されたようですが、何故でしょうか？

**Comment by syuilo** [comment]
https://github.com/syuilo/aiscript/actions/runs/6140933887/job/16660540179 のエラーが出るのと、CJSはレガシーだから必要なさそうと思った
