### ISSUE TITLE
エラークラスの名前を変えたい

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#351]
`SyntaxError`と`TypeError`を何か別の名称にしたい。
https://github.com/syuilo/aiscript/blob/master/src/error.ts
- EcmaScript標準のものと名前が被っている。
これにより、例えばimportせずに使ってしまっても気づかないなどの問題がある。
- 現に https://github.com/syuilo/aiscript/blob/master/src/type.ts ではTypeErrorが使用されているのにimportされていない

**Comment by FineArchs** [comment]
`AiSyntaxError` `AiTypeError`とか…？

**Comment by syuilo** [comment]
`AiScriptSyntaxError` / `AiScriptTypeError`で良さそう

**Comment by FineArchs** [comment]
統一性のために`RuntimeError`と`IndexOutOfRangeError`の名前も変えたりはとりあえずしなくてもいいですかね？

**Comment by syuilo** [comment]
したい
