### ISSUE TITLE
type.tsでTypeErrorがimportされていないのは意図的？

### ISSUE THREAD

**Issue by FineArchs** [syuilo/aiscript#356]
src/type.tsではTypeErrorが使用されている（https://github.com/syuilo/aiscript/blob/36fab971b20a6086f2493fb4f168907abad96fe2/src/type.ts#L52 ）にも関わらずerror.tsからTypeErrorがimportされていませんが、これはECMAScript標準のTypeErrorを使用するための意図的なものである可能性があります。
修正は必要でしょうか？
## 備考
- 該当のTypeErrorは内部的な不整合のさいに発生するものであり、内部エラーではAiScriptErrorを投げないという理念（もし存在するのであれば）に従えば現状が妥当です。
- ソース全体でTypeErrorの使用箇所は、ECMAScript・AiScript問わずここだけのようです。https://github.com/search?q=repo%3Asyuilo%2Faiscript%20TypeError&type=code

**Comment by syuilo** [comment]
cc: @marihachi

**Comment by marihachi** [comment]
後から追加されたコードみたいです。
https://github.com/syuilo/aiscript/blob/36fab971b20a6086f2493fb4f168907abad96fe2/src/type.ts#L58-L67 
最初に左右のtypeが一致していることを確認しているので、実際にassertTSimpleで例外は投げられることはないはずです。
なので単純なキャストでも可。

投げるエラーについても、実装当時はなかったものでAiScript側で用意したエラーに書き換えてもいいと思います。

**Comment by FineArchs** [comment]
ありがとうございます。了解です。
