### ISSUE TITLE
#313 の更新内容がCHANGELOGに記載されていない

### ISSUE THREAD

**Issue by saki-lere** [syuilo/aiscript#365]
#313 の更新内容がCHANGELOGに記載されていない
`0.16.0`の所に入るはず。

**Comment by FineArchs** [comment]
次バージョンの末尾などに
>## Note
>バージョン0.16.0に記録漏れがありました。
>- 関数`Str:from_codepoint` `Str#codepoint_at`を追加

みたいに書くと良さそうですかね？

**Comment by saki-lere** [comment]
情報が散らばるし実装自体されてるから0.16.0の欄に(も)書いた方がいい気がする

**Comment by FineArchs** [comment]
確かに
では両方書きましょうか

**Comment by FineArchs** [comment]
https://github.com/syuilo/aiscript/commit/dc0475eb7c2359ea0e8f7fd51d2774ccf0a805b1
修正しました。
