### ISSUE TITLE
1行に複数の文を書けない仕様に矛盾している？

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#385]
テストを見ている限りでは、
1行に複数の文は書けないので以下のコードは無効です:
```
let a = 42 let b = 11
```

しかし以下のようなテストもあります:
```
for 10 count += 1
```
こちらも構文解析上は1行に文が2つ並んでることになりますが、
for文のように子を持つ文の場合は有効というような仕様を考えてるんでしょうか

仕様の矛盾なのか、意図された仕様だったのか分からないので質問です。

**Comment by saki-lere** [comment]
その2つは構文上別物ではないですか？

「1行に複数の文を書けない」というより「(並列の)文同士を改行で区切る」という解釈の方が一般的なように思います
`for 10 count += 1`全体で1つの文、中身の行を増やすなら`{}`で範囲を明示して改行で区切る、といった感じ
```
for 10 {count += 1
count +=2}
```

**Comment by marihachi** [comment]
なんとなく違いは掴めました
複文に限って改行が必要って感じですかね？

**Comment by saki-lere** [comment]
そうだと思います。`;`の代わりに改行で区切る
