### ISSUE TITLE
各ノードが対応するコードの位置を返すように

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#78]
ノードにlocプロパティを追加して、入力コード上の対応する位置を取得できるようにする。

現状、AttributeはMapの要素としてdefノードに付加する形でパーサから返される。
 → Attributeもノードとして返されるように変更する？(要検討)

良さそうなら作業してPRを投げます

## ノードに位置が付加されるイメージ
入力コード:
```
<: "hello"

+ Event "Recieved"
@onRecieved(data) {
	data
}
```
パース結果:
```
[
  {
    type: 'call',
    name: 'print',
    args: [
      {
        type: 'str',
        value: 'hello',
        loc: { start: 3, end: 9 }
      }
    ],
    loc: { start: 0, end: 9 }
  },
  {
    type: 'def',
    name: 'onRecieved',
    expr: { ... },
    mut: false,
    attr: [
      { type: 'attr', name: 'Event', value: { type: 'str', value: 'Recieved', loc: { start: 20, end: 29 } }, loc: { start: 12, end: 29 } }
    ],
    loc: { start: 31, end: 57 }
  }
]
```

## 利用例
- 意味解析の段階で文法エラーが発生した場合にソースコード上の位置を示す
- ノードの位置情報を元に、その部分を取り除く
- ノードの位置情報を元に、その前後にコードを挿入する

**Comment by syuilo** [comment]
> Attributeもノードとして返されるように変更する

そうした場合のメリット知りたい

**Comment by marihachi** [comment]
そのAttributeの入力コード上の位置が分かるようになる
(全てのノードが位置を返すようになるため)

**Comment by marihachi** [comment]
def.attrにAttributeが付加されるのは変わらない

**Comment by marihachi** [comment]
意味解析の段階で文法エラーが発生した場合、ソースコード上の位置を示すこともできるようになる

**Comment by syuilo** [comment]
LGTM

**Comment by marihachi** [comment]
ｲｴｰ
