### ISSUE TITLE
ブール値の表記の提案

### ISSUE THREAD

**Issue by marihachi** [syuilo/aiscript#97]
`+` `-` によるブール値の表記は、他の構文と被っているので廃止するのはどうでしょう
`yes` `no`の方が直感的で、よく使われているように思う。

**Comment by syuilo** [comment]
`+`  `-` は廃止で良いと思う
`true` `false` でも良いかもしれない

**Comment by syuilo** [comment]
JSONをそのままAiScriptコードとして解釈できるようにするためにも、true / false が良さそう
yes / no も残して良いかもしれないけど

**Comment by marihachi** [comment]
bool値はtrue, falseだけにして、その他を廃止でいく？

**Comment by syuilo** [comment]
YOSASOU
